"use strict";
const $=id=>document.getElementById(id);let plainText="";
const blockTags=new Set(["ADDRESS","ARTICLE","ASIDE","BLOCKQUOTE","DIV","FOOTER","H1","H2","H3","H4","H5","H6","HEADER","HR","MAIN","NAV","P","SECTION","TR"]);
function normalize(text){return text.replace(/\u00a0/g," ").replace(/[ \t]+\n/g,"\n").replace(/\n[ \t]+/g,"\n").replace(/[ \t]{2,}/g," ").replace(/\n{3,}/g,"\n\n").trim()}
function linkText(node,options){const label=normalize(walkChildren(node,options)).trim();const href=(node.getAttribute("href")||"").trim();if(!options.links||!href||href.startsWith("#")||/^(mailto:|tel:)/i.test(href))return label||href.replace(/^(mailto:|tel:)/i,"");const visible=label.toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"");const target=href.toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"");return label&&visible===target?label:label?`${label} (${href})`:href}
function walkChildren(node,options){return Array.from(node.childNodes).map(child=>walk(child,options)).join("")}
function walk(node,options){if(node.nodeType===Node.TEXT_NODE)return node.nodeValue.replace(/\s+/g," ");if(node.nodeType!==Node.ELEMENT_NODE)return"";const tag=node.tagName;if(["SCRIPT","STYLE","TEMPLATE","NOSCRIPT","HEAD","TITLE","META","LINK","SVG","CANVAS"].includes(tag))return"";const hidden=node.hasAttribute("hidden")||node.getAttribute("aria-hidden")==="true"||/display\s*:\s*none|visibility\s*:\s*hidden/i.test(node.getAttribute("style")||"");if(hidden)return"";if(tag==="BR")return"\n";if(tag==="HR")return"\n----------------------------------------\n";if(tag==="IMG"){const alt=(node.getAttribute("alt")||"").trim();return options.images&&alt?`[Image: ${alt}]`:""}if(tag==="A")return linkText(node,options);if(tag==="LI"){const marker=node.parentElement?.tagName==="OL"?`${Array.from(node.parentElement.children).indexOf(node)+1}. `:"- ";return"\n"+marker+normalize(walkChildren(node,options))+"\n"}if(tag==="TD"||tag==="TH")return normalize(walkChildren(node,options))+"\t";let content=walkChildren(node,options);if(/^H[1-6]$/.test(tag)&&options.headings)content=content.toUpperCase();if(tag==="BLOCKQUOTE")content=normalize(content).split("\n").map(line=>"> "+line).join("\n");return blockTags.has(tag)?"\n"+content+"\n":content}
function convert(){const html=$("htmlInput").value;if(!html.trim()){plainText="";renderOutput();return}const doc=new DOMParser().parseFromString(html,"text/html");plainText=normalize(walkChildren(doc.body,{links:$("includeLinks").checked,images:$("includeImages").checked,headings:$("uppercaseHeadings").checked}));renderOutput()}
function sourceStats(){const html=$("htmlInput").value;const doc=new DOMParser().parseFromString(html,"text/html");$("sourceStats").innerHTML=`<span>${html.length.toLocaleString()} characters</span><span>${doc.querySelectorAll("a").length} links</span><span>${doc.querySelectorAll("img").length} images</span>`}
function renderOutput(){const words=plainText?plainText.split(/\s+/).length:0;const bytes=new TextEncoder().encode(plainText).length;$("plainOutput").value=plainText;$("emptyState").hidden=Boolean(plainText);$("status").textContent=plainText?"Conversion ready":"Waiting for HTML";$("status").classList.toggle("ready",Boolean(plainText));$("outputStats").innerHTML=`<div><strong>${words}</strong><span>Words</span></div><div><strong>${plainText.length.toLocaleString()}</strong><span>Characters</span></div><div><strong>${words?Math.max(1,Math.ceil(words/200)):0} min</strong><span>Read time</span></div><div><strong>${bytes<1024?bytes+" B":(bytes/1024).toFixed(1)+" KB"}</strong><span>Text size</span></div>`;$("copyButton").disabled=!plainText;$("downloadButton").disabled=!plainText;$("feedback").textContent=plainText?"Review the result, then copy or download it.":"Paste an HTML email or load the example to begin."}
$("htmlInput").addEventListener("input",()=>{sourceStats();convert()});["includeLinks","includeImages","uppercaseHeadings"].forEach(id=>$(id).addEventListener("change",convert));$("convertButton").addEventListener("click",()=>{convert();if(plainText){$("plainOutput").focus();$("feedback").textContent="Converted. Review the text before using it."}});$("copyButton").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(plainText);$("feedback").textContent="Plain text copied."}catch{$("plainOutput").focus();$("plainOutput").select();$("feedback").textContent="Copy was blocked. The text is selected; press Ctrl+C or Command+C."}});$("downloadButton").addEventListener("click",()=>{const url=URL.createObjectURL(new Blob([plainText+"\n"],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="email-plain-text.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$("feedback").textContent="Plain-text file downloaded."});$("clearButton").addEventListener("click",()=>{$("htmlInput").value="";plainText="";sourceStats();renderOutput();$("htmlInput").focus()});$("sampleButton").addEventListener("click",()=>{$("htmlInput").value=`<!DOCTYPE html>\n<html>\n<head><style>body { font-family: Arial; }</style></head>\n<body>\n  <div style="display:none">Hidden inbox preview</div>\n  <h1>September at Robust Email</h1>\n  <p>Hello Ayan,</p>\n  <p>Here are this month’s highlights:</p>\n  <ul><li>A cleaner editor</li><li>More reliable templates</li></ul>\n  <p><a href="https://example.com/news">Read the full update</a></p>\n  <img src="team.jpg" alt="The Robust Email team">\n  <p>Thanks,<br>The Robust Email team</p>\n</body>\n</html>`;sourceStats();convert();$("feedback").textContent="Example converted. Try changing the preferences."});sourceStats();renderOutput();
